<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-0356DV5C" ignored="0" name="t2" tests="1" failures="1" timestamp="2022-05-02T18:39:40 CST" time="7.214" errors="0">
  <testcase name="test111" time="0.003" classname="com.webtest.testCases.test1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at com.webtest.testCases.test1.test111(test1.java:14)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test111 -->
</testsuite> <!-- t2 -->
