<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-0356DV5C" ignored="0" name="t2" tests="5" failures="5" timestamp="2022-05-02T17:44:07 CST" time="24.899" errors="0">
  <testcase name="test_login" time="11.907" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.webtest.testCases.LoginTest.test_login(LoginTest.java:32)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- test_login -->
  <testcase name="test_warehourse_search" time="0.062" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.webtest.testCases.LoginTest.test_warehourse_search(LoginTest.java:209)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test_warehourse_search -->
  <testcase name="test_warehourse_add" time="2.03" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.webtest.testCases.LoginTest.test_warehourse_add(LoginTest.java:184)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test_warehourse_add -->
  <testcase name="test_warehourse_update" time="2.039" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.webtest.testCases.LoginTest.test_warehourse_update(LoginTest.java:153)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test_warehourse_update -->
  <testcase name="test_delete_success" time="2.028" classname="com.webtest.testCases.LoginTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
at java.util.ArrayList.rangeCheck(Unknown Source)
at java.util.ArrayList.get(Unknown Source)
at com.webtest.testCases.LoginTest.test_delete_success(LoginTest.java:138)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test_delete_success -->
</testsuite> <!-- t2 -->
